[package]
name = "libcitadel"
version = "0.1.0-beta"
description = "C-language bindings for Citadel runtime"
authors = ["Dr Maxim Orlovsky <orlovsky@mycitadel.io>"]
license = "MIT"
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["staticlib"]
name = "citadel"

[build-dependencies]
cbindgen = "0.16"
openssl = { version = "^0.10", features = ["vendored"] }

[dependencies]
libc = "0.2"
amplify = "3"
amplify_derive = "2.4"
citadel = { git = "https://github.com/LNP-BP/rust-lnpbp" }
# slip132 = "0.3.2"
# strict_encoding = { version = "1.0.7", features = ["chrono", "crypto", "miniscript", "derive"] }
lnpbp = "0.4"
lnpbp_invoice = { git = "https://github.com/LNP-BP/rust-lnpbp" }
# lnp-core = { git = "https://github.com/LNP-BP/lnp-core" }
rgb-core = "0.4.2"
rgb20 = "0.4"
# rgb_node = { git = "https://github.com/rgb-org/rgb-node", default-features = false, features = ["fungibles"] }
internet2 = { git = "https://github.com/internet2-org/rust-internet2" }
microservices = { git = "https://github.com/internet2-org/rust-internet2", default-features = false }
bech32 = "0.7"
bitcoin = "0.26"
descriptor-wallet = "0.4"
miniscript = "5.1"
bip39 = "1.0.0-rc1"
rand = "0.8.3"
base64-compat = "1.0.0"

log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5"
serde_with_macros = "~1.2.0" # Fix for the problem in 1.3.0
serde_json = "1"

[patch.crates-io]
# Required to fix Android SystemTime incorrect size
lightning-invoice = { git = "https://github.com/LNP-BP/rust-lightning-invoice", tag = "systemtime-fix" }
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }

[target.'cfg(target_os="android")'.dependencies]
android_logger = "~0.8.6"

[target.'cfg(not(target_os="android"))'.dependencies]
env_logger = "~0.7.1"

[target.'cfg(any(target_os="android", target_os="ios"))'.dependencies.zmq]
version = "~0.9.2"
features = ["vendored"]

[target.'cfg(any(target_os="android", target_os="ios"))'.dependencies.libsqlite3-sys]
version = "~0.18.0"
features = ["bundled"]
